### ISSUE TITLE
Spacemacs not receiving proper id, Missing required parameter: client_id

### ISSUE THREAD

**Issue by romanakmath** [mhkc/google-calendar-layer#9]
Good day, 

My spacemacs runs on windows, I followed your instructions.  I put 
`(setq org-gcal-client-id "YourClientId"
      org-gcal-client-secret "YourSecret")`
inside the user-config with the corresponding client id and yoursecret
But every time I open spacemacs and have a google-calendar layer I get redirected to the google page, which states
![error](https://user-images.githubusercontent.com/18005462/52440607-814b9580-2b16-11e9-9821-02ebd13e8e6e.PNG)
What am I doing wrong?

**Comment by bobberb** [comment]
You are not doing anything wrong. 

Manually edit the url by adding "YourClientID" after client= and before the &. This will get you the code. Some error in URL construction right now.

**Comment by romanakmath** [comment]
If I insert the id I indeed get redirected to the google site, where I login and get the code.
But after putting it in "Enter the code your browser displayed" 
![Enter the code your browser displayed](https://user-images.githubusercontent.com/18005462/55075408-d32a8980-508a-11e9-99c0-c3ef44bc1fb4.PNG)
I get the error http 401.
![Http error](https://user-images.githubusercontent.com/18005462/55075691-86937e00-508b-11e9-96e4-b61d155cb62f.PNG)
What can I do to get it to work? I assume spacemacs actually shouldn't reopen after entering the code or should it?

**Comment by bobberb** [comment]
I did a fresh install to test.

I did get a 404 first. I kept getting the same error 3x, the first time I
inserted the client ID into the URL and pasting in their given code each
time. Eventually, it went through.

**Comment by romanakmath** [comment]
Still no success unfortunately, but I also get an error 401 each time, which is different.

**Comment by bobberb** [comment]
If the 404 is replaced with a 401:

Try ``SPC a g f``

**Comment by romanakmath** [comment]
Now I receive an
D:/Google Drive/Documents/My notes.org and d:/Google Drive/Documents/My notes.org are the same file
org-gcal--archive-old-event: Org-gcal error: Couldn’t parse d:/Google Drive/Documents/My notes.org
error.

As proposed in the setup I wrote the following lines in the configuration file
  (setq org-gcal-file-alist '(("**@group.calendar.google.com" . "D:/Google Drive/Documents/My notes.org")))
  (setq org-agenda-files
        (quote ( "D:/Google Drive/Documents/My notes.org")))
I already tried to comment one of them out with no success

**Comment by bobberb** [comment]
I think an independent gcal.org is required, it cannot merge - it overrides.

**Comment by romanakmath** [comment]
I got it to work by using a new org file as you suggested and adding only  (setq org-gcal-file-alist '(("****@group.calendar.google.com" . "D:/Google Drive/Documents/gcal.org"))) and not the agenda file to the configuration, amazing! I know there is an option to set the alarm notice before the events in google calendar, can you also set them in the org file?

**Comment by bobberb** [comment]
I don't believe that information is currently probed.

**Comment by romanakmath** [comment]
Ok, that's fine. I suppose the issue can be closed, since I finally got the layer to work.

**Comment by bobberb** [comment]
@Rareform  please close.
